export interface CurriculumStage {
  id: string;
  title: string;
  description: string;
  icon: string; // matches a key in the STAGE_ICONS map in LearnPage
  challengeIds: string[];
}

export const CURRICULUM: CurriculumStage[] = [
  {
    id: "foundations",
    title: "Python Foundations",
    description: "Strings, lists, loops, and the building blocks every Python developer needs.",
    icon: "BookOpen",
    challengeIds: [
      "reverse-a-string",
      "count-vowels",
      "find-max-in-list",
      "longest-word",
      "capitalize-words",
      "chunk-list",
      "sum-of-digits",
      "count-occurrences",
      "prime-checker",
      "most-frequent",
    ],
  },
  {
    id: "patterns",
    title: "String & List Patterns",
    description: "Common manipulation techniques and problem-solving patterns used every day.",
    icon: "Brackets",
    challengeIds: [
      "check-anagram",
      "remove-duplicates",
      "is-palindrome",
      "two-sum",
      "flatten-list",
      "rotate-list",
      "string-compression",
      "longest-common-prefix",
      "matrix-diagonal-sum",
      "missing-number",
      "longest-unique-substring",
    ],
  },
  {
    id: "algorithms",
    title: "Algorithms",
    description: "Sorting, searching, and thinking carefully about time and space efficiency.",
    icon: "Cpu",
    challengeIds: [
      "fizzbuzz",
      "fibonacci",
      "is-power-of-two",
      "binary-search",
      "bubble-sort",
      "selection-sort",
      "insertion-sort",
      "climbing-stairs",
      "merge-sorted-lists",
      "max-subarray",
      "count-primes",
      "merge-intervals",
    ],
  },
  {
    id: "data-structures",
    title: "Data Structures",
    description: "Stacks, queues, recursion, hashing, and graph traversal.",
    icon: "Database",
    challengeIds: [
      "stack-push-pop",
      "queue-using-list",
      "valid-parentheses",
      "min-stack",
      "sum-nested-list",
      "group-anagrams",
      "lru-cache-simulation",
      "bfs-shortest-path",
    ],
  },
  {
    id: "oop",
    title: "Object-Oriented Python",
    description: "Classes, state, inheritance, and modelling real-world concepts with objects.",
    icon: "Layers",
    challengeIds: [
      "bank-account",
      "temperature-converter",
      "simple-calculator",
      "shape-area",
      "todo-list",
      "library-catalog",
      "plugin-registry",
    ],
  },
  {
    id: "best-practices",
    title: "Clean Code & Best Practices",
    description: "Write code that is clear, concise, Pythonic, and easy to maintain.",
    icon: "CheckCircle2",
    challengeIds: [
      "list-comprehension",
      "guard-clauses",
      "dict-comprehension",
      "label-items",
      "zip-to-dict",
      "normalize-user-records",
      "flatten-dict",
      "validate-config",
    ],
  },
  {
    id: "scripting",
    title: "Scripting & Automation",
    description: "Real-world scripts: parsing text, processing files, and building useful tools.",
    icon: "Terminal",
    challengeIds: [
      "word-frequency",
      "caesar-cipher",
      "validate-email",
      "file-name-sanitizer",
      "csv-row-parser",
      "log-parser",
      "template-filler",
      "number-to-roman",
      "ini-section-parser",
    ],
  },
];
